# Generated by Django 4.2.13 on 2024-07-08 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomuser',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_detail', to='core.chatroom'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 15, 42, 20, 149919)),
        ),
    ]
