# Generated by Django 4.2.13 on 2024-06-07 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 12, 17, 44, 784466)),
        ),
    ]
