# Generated by Django 4.2.13 on 2024-07-09 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chatroomuser_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 11, 44, 27, 868103)),
        ),
    ]
