# Generated by Django 5.0.6 on 2024-06-03 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messagereadstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageReadStatus',
            new_name='Notifications',
        ),
    ]
