# Generated by Django 4.2.13 on 2024-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membership_membershippayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_customer_id',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_subscription_id',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
