# Generated by Django 4.2.13 on 2024-06-06 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 8, 23, 29, 446139)),
        ),
    ]
